apiVersion: v1
entries:
  mibserver:
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2021-11-30T02:47:37.322607451Z"
    description: A Helm chart for serving mib files
    digest: fd08a5148acb76d7222b429fd287999fee33a206692b66458b521811746e1225
    name: mibserver
    type: application
    urls:
    - https://pysnmp.github.io/mibs/charts/mibserver-1.3.2.tgz
    version: 1.3.2
generated: "2021-11-30T02:47:37.321827824Z"
