apiVersion: v1
entries:
  mibserver:
  - apiVersion: v2
    appVersion: 1.3.4
    created: "2021-12-01T17:24:15.270720991Z"
    description: A Helm chart for serving mib files
    digest: 6589cb003a8c79361ce0b54e7a48bc3533af495f36563809bc2a8a9a8bb32632
    name: mibserver
    type: application
    urls:
    - https://pysnmp.github.io/mibs/charts/mibserver-1.3.4.tgz
    version: 1.3.4
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2021-11-30T02:47:37.322607451Z"
    description: A Helm chart for serving mib files
    digest: fd08a5148acb76d7222b429fd287999fee33a206692b66458b521811746e1225
    name: mibserver
    type: application
    urls:
    - https://pysnmp.github.io/mibs/charts/mibserver-1.3.2.tgz
    version: 1.3.2
generated: "2021-12-01T17:24:15.269893183Z"
