apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mibserver.fullname" . }}
  labels: 
    {{- include "mibserver.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- include "mibserver.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
    - Egress
