name: cd-pages-helm

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  mike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d / -f 3 | sed 's/v//')"
          if [[ $VERSION != *"develop"* ]]; then
            pip3 install poetry
            poetry install
            poetry run mike deploy -p -u "$VERSION" latest
          fi
  helm:
    runs-on: ubuntu-latest
    needs: mike
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3
      - name: Upload
        run: |
          mkdir /tmp/package
          mkdir /tmp/index
          mkdir /tmp/origin
          VERSION="$(echo "$GITHUB_REF" | cut -d / -f 3)"
          helm package charts -d /tmp/package
          gh release upload "$VERSION" /tmp/package/*
          helm repo index /tmp/package --url https://github.com/pysnmp/mibs/releases/download/"$VERSION"
          cp /tmp/package/index.yaml ./output
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true